### ISSUE TITLE
Some issues with Sameboy on retroplayer (libreelec 9.x) with RPI3b+

### ISSUE THREAD

**Issue by wwark** [kodi-game/game.libretro.sameboy#3]
Hi

Not sure it is the right place to open this ticket.

1st issue:
- No option for this game.libretro.sameboy
- Retroarch propose some options for this core like possibility to change the bios and be able to play gb game with a gbc bios.

2nd issue:
I have a blackscreen during the play of the game. 
If I go to the retroplayer menu of Kodi, the core is in pause mode and it shows a screen the game. 
If i stop the pause the black screen appeard again and if I go agian to retroplayer menu the screen show a new screen indicating the game is running meanwhile I have a black screen during the time the game is not in pause mode.

Thanks for your help,
Wwark.

**Comment by garbear** [comment]
For the first issue, it sounds like you want libretro settings, go to Menu -> Settings -> Advanced settings.

For the second issue, this is similar to what's reported in https://github.com/xbmc/xbmc/pull/14522. Can you upload a debug log?

**Comment by wwark** [comment]
![dsc_0264](https://user-images.githubusercontent.com/469461/49169597-63093280-f33a-11e8-9998-c93216d3a5ee.JPG)
![dsc_0265](https://user-images.githubusercontent.com/469461/49169598-63093280-f33a-11e8-949d-1f8804d23c1f.JPG)

As you can see, there is no configuration for sameboy. I add also a picture for mgba to show the differences.
I confirm if I select Advanced Settings for sameboy there is a popup indicating "this add-on can't be configured'

I put "99." in the begining of the version of the game libretro because we have issues in the repo of libreelec about game.libretro.*

I will send you the logs for the second issue. 

Thanks,
Wwark

**Comment by wwark** [comment]
[kodi.log](https://github.com/kodi-game/game.libretro.sameboy/files/2625990/kodi.log)
The kodi.log is in attachment.
Thanks,
Wwark

**Comment by wwark** [comment]
More information I did some test on others emulator Nestopia and FCEUMM.
I have the same issue with Nestopia (balck screen) and I don't have the issue with FCEUMM.

Thanks,
Wwark

**Comment by garbear** [comment]
@VelocityRA was the last one to touch the GL code, but he's working on something really exciting, so I'll wait a while to bug him about this :) @lrusak were you ever able to reproduce the black screens?

**Comment by lrusak** [comment]
Nope, but I can try and look into it more this weekend

**Comment by wwark** [comment]
Hi @all,
Do you have update on this issue ?
For information => https://forum.libreelec.tv/thread/4858-9-0-devel-libreelec-builds-for-mx2-g18/?postID=104461#post104461 someone have also the same issue in Nestopia.

Thanks for your help

**Comment by wwark** [comment]
Hi,

I switched to a nuc PC and still using libreelec 9.0.
Sameboy work (no black screen) meanwhile I don't have any sound. Do you have sound on your side?
I tried the same rom with gambatte and I have sound.

I add a PR with the Icon and the setting.xml maybe it might help for these issues.

thanks,
Wwark

**Comment by wwark** [comment]
New update after some tests, the sound work in kodi retroplayer on windows.
The sound issue maybe just present on replayer of libreelec.

**Comment by wwark** [comment]
Hi,

This issue is not present anymore with the new version *.106.
I close this ticket.

Thanks,
Wwark.
