### ISSUE TITLE
New release version is lower then existing

### ISSUE THREAD

**Issue by CvH** [kodi-game/game.libretro.sameboy#5]
### Describe the bug
New released version is lower then existing one so no update is possible at least for Leia and Matrix likely too.
0.12.0.11-Leia > 0.0.1.12-Leia
https://github.com/kodi-game/game.libretro.sameboy/commit/7cb7cdf9e0721daa81881349f35b4642c234701a

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

Kodi version: Leia/Master

**Comment by CvH** [comment]
fixed with latest release

**Comment by garbear** [comment]
Missed this. You can tag me next time. Thanks for reporting.
